{% set data = load_setup_py_data() %}

package:
  name: tomopackets
  version: {{ data['version'] }}

source:
  # path: ../
  git_url: https://github.com/cicwi/TomoPackets
  git_tag: main

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

test:
  imports:
    - tomop

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - python
    - pip
    - boost-cpp
    - pybind11
    - zeromq=4
  run:
    - python
    - zeromq=4

about:
  home: https://github.com/cicwi/TomoPackets
  license: GPLv3
  summary: 'Tomopackets'
